local JC = {}

-- Navbar
JC.NAVBAR_H = 40
JC.NAVBAR_BG = Color3.fromRGB(20, 18, 28)
JC.TAB_WIDTH = 100
JC.TAB_GAP = 20

-- Colors (общие)
JC.BG_COLOR = Color3.fromRGB(10, 8, 14)
JC.TEXT_COLOR = Color3.fromRGB(220, 220, 220)
JC.TEXT_DIM = Color3.fromRGB(140, 140, 160)
JC.ACCENT = Color3.fromRGB(100, 25, 25)
JC.STROKE_COLOR = Color3.fromRGB(80, 80, 100)
JC.CLOSE_BG = Color3.fromRGB(60, 30, 30)
JC.CLOSE_TEXT = Color3.fromRGB(200, 100, 100)

-- Background images per context
JC.DEFAULT_BG = "rbxassetid://130567382079214"
JC.SCHOOL_BACKGROUNDS = {
    Blood = "rbxassetid://130567382079214", -- "rbxassetid://76367891618899",
    Chaos = "rbxassetid://130567382079214" -- "rbxassetid://91208608367576"
}

return JC
