return {
    Stations = {
        Sawmill = {
            Name = "Лесопилка",
            InputSlots = 8,
            OutputSlots = 8,
            InteractRange = 10,
            -- Цвет модели при крафте
            CraftingColor = Color3.fromRGB(180, 140, 60)
        },
        Crusher = {
            Name = "Дробилка",
            InputSlots = 8,
            OutputSlots = 8,
            InteractRange = 10,
            CraftingColor = Color3.fromRGB(140, 140, 180)
        }
    }
}
