return {
    blood_ring = {
        Name = "Кровавое кольцо",
        Description = "Кольцо, пропитанное кровавой эссенцией.",
        Icon = "rbxassetid://78556678380740",
        Type = "Ring",
        EquipSlot = "Ring",
        ItemLevel = 6,
        Stackable = false,
        MaxStack = 1,
        Stats = {
            PhysicalPower = 3,
            MagicalPower = 2
        }
    },
    blood_necklace = {
        Name = "Кровавое ожерелье",
        Description = "Ожерелье, наполненное силой крови.",
        Icon = "rbxassetid://133439572731065",
        Type = "Amulet",
        EquipSlot = "Amulet",
        ItemLevel = 6,
        Stackable = false,
        MaxStack = 1,
        Stats = {
            MaxHP = 15,
            HealthRegen = 0.1
        }
    },
    small_bag = {
        Name = "Small Bag",
        Description = "A small leather bag. Unlocks 1 extra inventory row.",
        Icon = "rbxassetid://133649527466179",
        Type = "Bag",
        EquipSlot = "Bag",
        ItemLevel = 1,
        Stackable = false,
        MaxStack = 1,
        BagData = {
            ExtraRows = 1
        }
    },
    large_bag = {
        Name = "Large Bag",
        Description = "A spacious bag. Unlocks 2 extra inventory rows.",
        Icon = "rbxassetid://122047544255898",
        Type = "Bag",
        EquipSlot = "Bag",
        ItemLevel = 3,
        Stackable = false,
        MaxStack = 1,
        BagData = {
            ExtraRows = 2
        }
    }
}
