return {
    iron_helmet = {
        Name = "Iron Helmet",
        Description = "Basic head protection.",
        Icon = "rbxassetid://130188795755158",
        Type = "Head",
        EquipSlot = "Head",
        ItemLevel = 5,
        Stackable = false,
        MaxStack = 1,
        Stats = {
            Defense = 5
        }
    },
    rugged_hide_helmet = {
        Name = "Hide Helmet",
        Description = "A rough helmet made from beast hides.",
        Icon = "rbxassetid://130188795755158",
        Type = "Head",
        EquipSlot = "Head",
        ItemLevel = 1,
        Stackable = false,
        MaxStack = 1,
        Stats = {
            HP = 10
        }
    },
    rugged_hide_chest = {
        Name = "Hide Chestplate",
        Description = "A sturdy chestpiece crafted from thick hides.",
        Icon = "rbxassetid://139222038886991",
        Type = "Chest",
        EquipSlot = "Chest",
        ItemLevel = 1,
        Stackable = false,
        MaxStack = 1,
        Stats = {
            HP = 10
        }
    },
    rugged_hide_legs = {
        Name = "Hide Leggings",
        Description = "Leggings stitched from layered beast hides.",
        Icon = "rbxassetid://112291375503087",
        Type = "Legs",
        EquipSlot = "Legs",
        ItemLevel = 1,
        Stackable = false,
        MaxStack = 1,
        Stats = {
            HP = 10
        }
    },
    rugged_hide_gauntlets = {
        Name = "Hide Gauntlets",
        Description = "Gauntlets wrapped in tough animal hide.",
        Icon = "rbxassetid://102807820827058",
        Type = "Hands",
        EquipSlot = "Hands",
        ItemLevel = 1,
        Stackable = false,
        MaxStack = 1,
        Stats = {
            HP = 10
        }
    },
    rugged_hide_boots = {
        Name = "Hide Boots",
        Description = "Boots reinforced with beast hide.",
        Icon = "rbxassetid://89717071091346",
        Type = "Feet",
        EquipSlot = "Feet",
        ItemLevel = 1,
        Stackable = false,
        MaxStack = 1,
        Stats = {
            HP = 10
        }
    }
}
