return {
    blood_essence = {
        Name = "Blood Essence",
        Description = "An energy source distilled from blood.",
        Icon = "rbxassetid://114549612188882",
        Category = "Alchemy",
        Type = "Resource",
        ItemLevel = 0,
        Stackable = true,
        MaxStack = 500
    },
    wood = {
        Name = "Wood",
        Description = "Raw wood harvested from trees.",
        Icon = "rbxassetid://120841469219855",
        Type = "Resource",
        ItemLevel = 0,
        Stackable = true,
        MaxStack = 99
    },
    stone = {
        Name = "Stone",
        Description = "Raw stone mined from rocks.",
        Icon = "rbxassetid://73029786735287",
        Type = "Resource",
        ItemLevel = 0,
        Stackable = true,
        MaxStack = 99
    },
    rugged_hide = {
        Name = "Rugged Hide",
        Description = "Thick hide stripped from wild beasts.",
        Icon = "rbxassetid://122691562832137",
        Type = "Resource",
        ItemLevel = 0,
        Stackable = true,
        MaxStack = 500
    },
    wooden_plank = {
        Name = "Доска",
        Description = "Обработанная древесина. Используется в строительстве.",
        Icon = "rbxassetid://0",
        Type = "Resource",
        ItemLevel = 0,
        Stackable = true,
        MaxStack = 500
    }
}
