return {
    Sword = {
        Name = "Sword of Light",
        Description = "A shining blade.",
        Icon = "rbxassetid://119544363190700",
        Type = "Weapon",
        ItemLevel = 1,
        Stackable = false,
        MaxStack = 1
    },
    Axe = {
        Name = "Iron Axe",
        Description = "A sturdy one-handed axe.",
        Icon = "rbxassetid://127853105217094",
        Type = "Weapon",
        ItemLevel = 1,
        Stackable = false,
        MaxStack = 1
    },
    Bow = {
        Name = "Hunting Bow",
        Description = "A reliable ranged weapon.",
        Icon = "rbxassetid://128697214807336",
        Type = "Weapon",
        ItemLevel = 1,
        Stackable = false,
        MaxStack = 1
    }
}
